// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: api/measurement/measurement.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MeasurementServiceClient is the client API for MeasurementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeasurementServiceClient interface {
	GetAllMeasurements(ctx context.Context, in *None, opts ...grpc.CallOption) (*Measurements, error)
}

type measurementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeasurementServiceClient(cc grpc.ClientConnInterface) MeasurementServiceClient {
	return &measurementServiceClient{cc}
}

func (c *measurementServiceClient) GetAllMeasurements(ctx context.Context, in *None, opts ...grpc.CallOption) (*Measurements, error) {
	out := new(Measurements)
	err := c.cc.Invoke(ctx, "/measurement.MeasurementService/GetAllMeasurements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeasurementServiceServer is the server API for MeasurementService service.
// All implementations must embed UnimplementedMeasurementServiceServer
// for forward compatibility
type MeasurementServiceServer interface {
	GetAllMeasurements(context.Context, *None) (*Measurements, error)
	mustEmbedUnimplementedMeasurementServiceServer()
}

// UnimplementedMeasurementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMeasurementServiceServer struct {
}

func (UnimplementedMeasurementServiceServer) GetAllMeasurements(context.Context, *None) (*Measurements, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMeasurements not implemented")
}
func (UnimplementedMeasurementServiceServer) mustEmbedUnimplementedMeasurementServiceServer() {}

// UnsafeMeasurementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeasurementServiceServer will
// result in compilation errors.
type UnsafeMeasurementServiceServer interface {
	mustEmbedUnimplementedMeasurementServiceServer()
}

func RegisterMeasurementServiceServer(s grpc.ServiceRegistrar, srv MeasurementServiceServer) {
	s.RegisterService(&MeasurementService_ServiceDesc, srv)
}

func _MeasurementService_GetAllMeasurements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(None)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeasurementServiceServer).GetAllMeasurements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/measurement.MeasurementService/GetAllMeasurements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeasurementServiceServer).GetAllMeasurements(ctx, req.(*None))
	}
	return interceptor(ctx, in, info, handler)
}

// MeasurementService_ServiceDesc is the grpc.ServiceDesc for MeasurementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeasurementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "measurement.MeasurementService",
	HandlerType: (*MeasurementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllMeasurements",
			Handler:    _MeasurementService_GetAllMeasurements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/measurement/measurement.proto",
}
