// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: internal/session/session.proto

package session

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SessionManagementServiceClient is the client API for SessionManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionManagementServiceClient interface {
	GetSessionInfo(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*SessionInfo, error)
}

type sessionManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionManagementServiceClient(cc grpc.ClientConnInterface) SessionManagementServiceClient {
	return &sessionManagementServiceClient{cc}
}

func (c *sessionManagementServiceClient) GetSessionInfo(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*SessionInfo, error) {
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, "/session.SessionManagementService/GetSessionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionManagementServiceServer is the server API for SessionManagementService service.
// All implementations must embed UnimplementedSessionManagementServiceServer
// for forward compatibility
type SessionManagementServiceServer interface {
	GetSessionInfo(context.Context, *SessionID) (*SessionInfo, error)
	mustEmbedUnimplementedSessionManagementServiceServer()
}

// UnimplementedSessionManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSessionManagementServiceServer struct {
}

func (UnimplementedSessionManagementServiceServer) GetSessionInfo(context.Context, *SessionID) (*SessionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionInfo not implemented")
}
func (UnimplementedSessionManagementServiceServer) mustEmbedUnimplementedSessionManagementServiceServer() {
}

// UnsafeSessionManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionManagementServiceServer will
// result in compilation errors.
type UnsafeSessionManagementServiceServer interface {
	mustEmbedUnimplementedSessionManagementServiceServer()
}

func RegisterSessionManagementServiceServer(s grpc.ServiceRegistrar, srv SessionManagementServiceServer) {
	s.RegisterService(&SessionManagementService_ServiceDesc, srv)
}

func _SessionManagementService_GetSessionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagementServiceServer).GetSessionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.SessionManagementService/GetSessionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagementServiceServer).GetSessionInfo(ctx, req.(*SessionID))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionManagementService_ServiceDesc is the grpc.ServiceDesc for SessionManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "session.SessionManagementService",
	HandlerType: (*SessionManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSessionInfo",
			Handler:    _SessionManagementService_GetSessionInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/session/session.proto",
}
